from __future__ import annotations

from pathlib import Path
from typing import Callable

import pandas as pd

from services.annual_etf_checkpoint import (
    AnnualCheckpointStore,
    _atomic_write_json,
    _frame_fingerprint,
    _restore_checkpoint_dates,
    _restore_selections,
    data_fingerprint,
    run_annual_etf_backtest_core,
)
from services.annual_etf_market import (
    _column,
    _normalize_actions,
    annual_raw_cache_key,
    dividends_for_symbol,
    exchange_prefixed_symbol,
    fetch_annual_dividends,
    fetch_annual_etf_raw_history,
    load_index_family_config,
    load_registry,
    normalize_annual_market_data,
    registry_frame,
    share_splits_for_symbol,
    stitch_proxy_history,
    validate_registry_against_whitelist,
)
from services.annual_etf_models import (
    ALL_SLOTS,
    ANNUAL_CACHE_PERIOD,
    ANNUAL_CACHE_SOURCE,
    ANNUAL_DIVIDEND_CACHE_KEY,
    ANNUAL_DIVIDEND_DATA_TYPE,
    ANNUAL_RAW_DATA_TYPE,
    DEFAULT_MA_PERIODS,
    DEFAULT_THRESHOLDS,
    EXECUTION_NEXT_CLOSE,
    EXECUTION_SAME_CLOSE,
    NON_US_SLOTS,
    PARKING_LISTING_DATE,
    PARKING_SLOTS,
    PARKING_SYMBOL,
    REGISTRY_VERSION,
    SCORE_WEIGHTS,
    US_SLOTS,
    WHITELIST_VERSION,
    AnnualBacktestSettings,
    AnnualEtfRegistryEntry,
    AnnualPortfolioResult,
    AnnualQualificationResult,
    AnnualSelection,
    DirectionSleeveState,
    HistoricalEtfRecord,
    _empty_frame,
    _normalize_symbol,
    _optional_text,
)
from services.annual_etf_report import (
    _summary_row,
    _yearly_table,
    build_markdown_report,
    calculate_direction_contribution,
)
from services.annual_etf_selection import (
    _apply_split,
    _best_parameter,
    _decision_date,
    _desired_states,
    _longest_underwater_days,
    _proxy_for_record,
    _research_leg,
    _research_window,
    _research_strategy,
    _selection_map,
    build_annual_selections,
    performance_metrics,
    preflight_annual_candidates,
    score_metrics,
    selections_frame,
)
from services.annual_etf_simulation import (
    _activate_selection,
    _annual_effective_dates,
    _apply_actions,
    _buy_active,
    _buy_half_long,
    _buy_parking,
    _initial_weights,
    _last_price,
    _price_row,
    _sell_current,
    _sell_parking,
    _signal_state,
    _simulate_annual_hold_benchmark,
    _simulate_parking_benchmark,
    _trade,
    _value_state,
    simulate_annual_portfolio,
)


# Keep dataclass/checkpoint identities and historical pickle paths stable while
# sharing the same class objects with the split implementation modules.
for _compatibility_type in (
    HistoricalEtfRecord,
    AnnualEtfRegistryEntry,
    AnnualBacktestSettings,
    AnnualSelection,
    AnnualQualificationResult,
    AnnualPortfolioResult,
    DirectionSleeveState,
    AnnualCheckpointStore,
):
    _compatibility_type.__module__ = __name__
del _compatibility_type


def run_annual_etf_backtest(
    records: list[HistoricalEtfRecord],
    whitelist: dict[str, object],
    market_data: dict[str, pd.DataFrame],
    settings: AnnualBacktestSettings,
    *,
    proxy_data: dict[str, pd.DataFrame] | None = None,
    checkpoint_dir: str | Path | None = None,
    progress_callback: Callable[[str, float], None] | None = None,
) -> AnnualPortfolioResult:
    """运行年度ETF回测，同时保留旧模块路径上的依赖替换能力。"""
    return run_annual_etf_backtest_core(
        records,
        whitelist,
        market_data,
        settings,
        proxy_data=proxy_data,
        checkpoint_dir=checkpoint_dir,
        progress_callback=progress_callback,
        preflight_fn=preflight_annual_candidates,
    )


__all__ = [
    "REGISTRY_VERSION",
    "WHITELIST_VERSION",
    "ANNUAL_CACHE_SOURCE",
    "ANNUAL_RAW_DATA_TYPE",
    "ANNUAL_DIVIDEND_DATA_TYPE",
    "ANNUAL_CACHE_PERIOD",
    "ANNUAL_DIVIDEND_CACHE_KEY",
    "DEFAULT_MA_PERIODS",
    "DEFAULT_THRESHOLDS",
    "SCORE_WEIGHTS",
    "EXECUTION_SAME_CLOSE",
    "EXECUTION_NEXT_CLOSE",
    "PARKING_SYMBOL",
    "PARKING_LISTING_DATE",
    "US_SLOTS",
    "NON_US_SLOTS",
    "ALL_SLOTS",
    "PARKING_SLOTS",
    "HistoricalEtfRecord",
    "AnnualEtfRegistryEntry",
    "AnnualBacktestSettings",
    "AnnualSelection",
    "AnnualQualificationResult",
    "AnnualPortfolioResult",
    "DirectionSleeveState",
    "load_registry",
    "load_index_family_config",
    "registry_frame",
    "validate_registry_against_whitelist",
    "annual_raw_cache_key",
    "exchange_prefixed_symbol",
    "fetch_annual_etf_raw_history",
    "fetch_annual_dividends",
    "dividends_for_symbol",
    "share_splits_for_symbol",
    "normalize_annual_market_data",
    "stitch_proxy_history",
    "preflight_annual_candidates",
    "performance_metrics",
    "score_metrics",
    "build_annual_selections",
    "selections_frame",
    "simulate_annual_portfolio",
    "calculate_direction_contribution",
    "build_markdown_report",
    "data_fingerprint",
    "AnnualCheckpointStore",
    "run_annual_etf_backtest",
    "_empty_frame",
    "_normalize_symbol",
    "_optional_text",
    "_column",
    "_normalize_actions",
    "_decision_date",
    "_research_window",
    "_proxy_for_record",
    "_desired_states",
    "_apply_split",
    "_research_leg",
    "_research_strategy",
    "_longest_underwater_days",
    "_best_parameter",
    "_selection_map",
    "_initial_weights",
    "_price_row",
    "_last_price",
    "_signal_state",
    "_trade",
    "_sell_parking",
    "_buy_parking",
    "_sell_current",
    "_activate_selection",
    "_buy_active",
    "_buy_half_long",
    "_annual_effective_dates",
    "_apply_actions",
    "_value_state",
    "_simulate_annual_hold_benchmark",
    "_simulate_parking_benchmark",
    "_yearly_table",
    "_summary_row",
    "_frame_fingerprint",
    "_atomic_write_json",
    "_restore_checkpoint_dates",
    "_restore_selections",
]
